### ISSUE TITLE
powerline_docker has no attribute docker

### ISSUE THREAD

**Issue by ReeSilva** [adrianmo/powerline-docker#5]
When I try to add the segment, I receive this error.

OS: Arch Linux
Python version: 3.5

```
^C2016-09-21 12:27:18,257:ERROR:shell:segment_generator:Failed to import attr docker from module powerline_docker: module 'powerline_docker' has no attribute 'docker'
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/powerline/__init__.py", line 382, in get_module_attr
    return getattr(__import__(module, fromlist=(attr,)), attr)
AttributeError: module 'powerline_docker' has no attribute 'docker'
2016-09-21 12:27:18,258:ERROR:shell:segment_generator:Failed to generate segment from {'priority': 10, 'function': 'powerline_docker.docker'}: Failed to obtain segment function
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/powerline/segment.py", line 328, in get
    contents, _contents_func, module, function_name, name = get_segment_info(data, segment)
  File "/usr/lib/python3.5/site-packages/powerline/segment.py", line 69, in get_function
    raise ImportError('Failed to obtain segment function')
ImportError: Failed to obtain segment function
```

**Comment by adrianmo** [comment]
@ReeSilva thanks for reporting the issue. I have identified the issue and will fix it right away.

**Comment by ReeSilva** [comment]
Nice. I'll be waiting :D

**Comment by ReeSilva** [comment]
Awesome, now it's working :+1: 

Just a doubt, how can I get the whale icon? There is any font pack that I need to install?

**Comment by adrianmo** [comment]
Nice! 

To get the whale icon you need to install the Powerline fonts: http://powerline.readthedocs.io/en/master/installation.html#fonts-installation

**Comment by ReeSilva** [comment]
@adrianmo I already have :/

**Comment by adrianmo** [comment]
Have you enabled them in your terminal app? I'm currently using iTerm2 with the font `Meslo for Powerline`

**Comment by ReeSilva** [comment]
Actually no, I'm using monospace on Gnome Terminal. But all other powerline chars (like dividers and etc) are working normally.

Check:
https://ibin.co/2vqbqduSsq2G.png

**Comment by adrianmo** [comment]
Looks like that font does not support these kind of unicode characters.

I would recommend you to use any of the fonts listed here: https://github.com/powerline/fonts

Running `echo "\U0001F433"` should display the whale icon.

![](http://oi66.tinypic.com/vwy9tx.jpg)

**Comment by ReeSilva** [comment]
Well, this make the things became more strange. Because I was using SourceCodePro and change to Mono to test, but neither works. Also trying with Roboto Mono and Terminus with no sucess.

I try to change the Terminal to XFCE terminal and it didn't work too :/

**Comment by adrianmo** [comment]
@ReeSilva can you try Meslo?

**Comment by ReeSilva** [comment]
Even with Meslo :/
